version: "3.8"

services:
  piano-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: piano-midi-player
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
